### ISSUE TITLE
Infinite recursion in fillLeftBelowEdgeEvent

### ISSUE THREAD

**Issue by hurzl** [orbisgis/poly2tri.java#5]
```
Caused by: java.lang.StackOverflowError: stack size 1036KB
at org.poly2tri.triangulation.delaunay.sweep.DTSweep.fillLeftConvexEdgeEvent(DTSweep.java:456)
at org.poly2tri.triangulation.delaunay.sweep.DTSweep.fillLeftBelowEdgeEvent(DTSweep.java:512)
at org.poly2tri.triangulation.delaunay.sweep.DTSweep.fillLeftBelowEdgeEvent(DTSweep.java:514)
at org.poly2tri.triangulation.delaunay.sweep.DTSweep.fillLeftBelowEdgeEvent(DTSweep.java:514)
at org.poly2tri.triangulation.delaunay.sweep.DTSweep.fillLeftBelowEdgeEvent(DTSweep.java:514)
...
```

**Comment by ebocher** [comment]
Any returns, any comments since 2015.
We can closed it ?
@nicolas-f

**Comment by hurzl** [comment]
can't remember

**Comment by ebocher** [comment]
Ok we close it
